name: TheWalls
version: 0.2
main: me.NerdsWBNerds.TheWalls.TheWalls
commands:
   tw:
      description: General TheWalls commands.
      usage: /<command> help
   map:
      description: Get map information.
      usage: /<command>
   info:
      description: Get's general information about all lobbies.
      usage: /<info>
      aliases: [lobby, lobbys]
   quit:
      description: Quit game and/or leave que.
      usage: /<command>
      aliases: [leave]
   join:
      description: Join the waiting que.
      usage: /<command>
   spec:
      description: Spectate someone.
      usage: /<command> <name>
      aliases: [spectate]
   wait:
      description: Teleport to waiting area.
      usage: /<command>
   setwait:
      description: Set waiting area.
      usage: /<command>
   setback:
      description: Set backup area.
      usage: /<command>
   add:
      description: Add new world at your location.
      usage: /<command>
   alldm:
      description: Force all worlds into deathmatch.
      usage: /<command>
      aliases: [forcedm, alldeath, alldeathmatch, dmall]
   record:
      description: Check people's records.
      usage: /<command> [name]
   top:
      description: Get the top people in kills, wins, and deaths.
      usage: /<command>
      aliases: [leader, lead, leaderboard, leaderboards]
   team:
      description: Without message, switch to team chat, with message, send single team message.
      usage: /<command> [message]
   g:
      description: Without message, switch to global chat, with message, send single global message.
      usage: /<command> [message]
      aliases: [global]
   invite:
      description: Request someone to join your team.
      usage: /<command> <player>
   accept:
      description: Join team last invited to.
      usage: /<command>
   quitteam:
      description: Leave whatever team you are currently in.
      usage: /<command>
      aliases: [leaveteam]